---
Name: workflowconfig
---
SiteTree:
  extensions:
    - WorkflowApplicable
CMSPageEditController:
  extensions:
    - AdvancedWorkflowExtension
GridFieldDetailForm_ItemRequest:
  extensions:
    - AdvancedWorkflowExtension
---
Name: workflow_jobs
Only:
  moduleexists: queuedjobs
---
Injector:
  WorkflowReminderJob:
    properties:
      queuedJobService: %$QueuedJobService
---
LeftAndMain:
  extra_requirements_css: css/AdvancedWorkflowAdmin.css